import Footer from "@/components/Footer";
import "./globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: "Next Social Network",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={"antialiased bg-neutral-900"}>
        <div className="flex flex-col h-screen">
          <Header />
          <div className="flex-grow container mx-auto px-4 lg:px-0">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
